Fantom-foundation/LaScala

carmen/race-detection.jenkinsfile
tosca/compliance-tests.jenkinsfile
tosca/validate-evmzero.jenkinsfile
tosca/validate-geth.jenkinsfile
tosca/validate-lfvm-si.jenkinsfile
tosca/validate-lfvm.jenkinsfile

This PR adds tosca jenkins tests for `google cloud`

Add tosca tests

---

aida-db_testing/autogen-mainnet.jenkinsfile
aida-db_testing/autogen-testnet.jenkinsfile
aida-db_testing/integration-mainnet-tests.jenkinsfile
aida-db_testing/integration-testnet-tests.jenkinsfile
aida-db_testing/mainnetUpdate.sh
aida-db_testing/pre-release-mainnet.jenkinsfile
aida-db_testing/pre-release-testnet.jenkinsfile
aida-db_testing/single-run-manual-updatedb-generate.jenkinsfile

Backing up all important aida-db jenkins jobs.

backup aida-db jobs

---

aida/CI.jenkinsfile

This PR migrates Aida CI pipeline to Github.  The code has been tested here https://scala.fantom.network/job/Aida/job/CI/17/. The whole pipeline took 1 days and 18 hours.

Add Aida CI tests

---

release_testing/functional_tests/F01.jenkinsfile
release_testing/functional_tests/F03.jenkinsfile

Add `--chainid` flag to testnet tests.

add testnet chain-id

---

aida/CI.jenkinsfile

Temporary disable statedb record and replay tests.

disable sdb record/replay tests

---

carmen/race-detection.jenkinsfile
carmen/stress-test.jenkinsfile
carmen/validate-cpp-file-s3.jenkinsfile
carmen/validate-go-file-s3.jenkinsfile
carmen/validate-go-s4.jenkinsfile
carmen/validate-go-s5-archive.jenkinsfile
carmen/validate-go-s5.jenkinsfile

This PR adds branch parameters to Race-Detection test which make it easy to change Carmen or Aida branch.

Add branch parameters to Carmen tests

---

release_testing/master.jenkinsfile
release_testing/operational_tests/P02.jenkinsfile
release_testing/operational_tests/P03.jenkinsfile

Updates genesis file parameter to newer one.
Decreases verbosity level of sonicd tool to save disk space - eliminates enormous logs.

P02 and P03 parameters update

---

carmen/stress-test.jenkinsfile

this PR removes dependency to Aida from the pipeline, as this dependency is not needed.

removes dependency to aida from stress test

---

carmen/stress-test-tool.jenkinsfile

This PR introduces a pipeline that executes stress test toolbox of carmen

introduces pipeline to execute carmen stress test tool

---

carmen/validate-witness-proof.jenkinsfile

This PR introduces pipeline to verify carmen witness proof

introduces pipeline to verify witness proof

---

release_testing/master.jenkinsfile
release_testing/operational_tests/P02.jenkinsfile
release_testing/operational_tests/P03.jenkinsfile

This PR needs to be merged together with PR #121

P02 and P03 update

---

carmen/fuzzing.jenkinsfile

This PR re-introduces fuzzing for Carmen

re-introduces fuzzing

---

carmen/validate-db-reset.jenkinsfile

This PR adds `validate-db-reset.jenkinsfile` which tests the `reset` feature in

Add validate-db-reset.jenkinsfile

---

carmen/validate-state-toolchain-init-archive.jenkinsfile

This PR introduces pipeline to test toolbox that initializes archive from live db

introduces pipeline to test toolbox that initializes archive from live db

---

release_testing/functional_tests/F02/master.jenkinsfile

Add 65m-70m and 70m-last block stages

Add new stage to split F02

---

carmen/stress-test-tool.jenkinsfile
carmen/stress-test.jenkinsfile

This PR redirects temp directory to a bigger disk

redirects tmp directory to a bigger volume disk

---

tosca/compliance-tests.jenkinsfile
tosca/fuzzing-tests.jenkinsfile
tosca/validate-evmzero.jenkinsfile
tosca/validate-geth.jenkinsfile
tosca/validate-lfvm-si.jenkinsfile
tosca/validate-lfvm.jenkinsfile

The path is now fixed in the VM for the jenkinsfile to use.

Remove PATH fix for rust

---

carmen/fuzzing.jenkinsfile

This PR changes fuzzing agent to a dedicated VM

updates fuzzing agent and set go cache

---

sonic/eth-tests.jenkinsfile

This PR creates a pipeline to run ethereum tests agains Sonic

executes eth-tests for Sonic client

---

sonic/race-detection-unit-tests.jenkinsfile

Race detection of Sonic unit tests
Test pipeline: https://scala.fantom.network/job/Sonic/job/Unit-test-race-detection/
[Part of](https://github.com/Fantom-foundation/sonic-admin/issues/47)

Add CI script for race detection

---

norma/test-export.jenkinsfile

Add nightly test for export function
Tested here: https://scala.fantom.network/job/Norma/job/Experimental/job/TestExport/

[Norma] Add nightly test for export function

---

norma/test-baseline.jenkinsfile

this PR changes execution of norma tests, it runs all test scenarios in a directory instead of a single file.

runs all Norma test scenarios

---

carmen/fuzzing.jenkinsfile
carmen/race-detection.jenkinsfile
carmen/stress-test-tool.jenkinsfile
carmen/stress-test.jenkinsfile
carmen/transient-storage.jenkinsfile
carmen/validate-cpp-file-s3.jenkinsfile
carmen/validate-db-reset.jenkinsfile
carmen/validate-go-file-s3.jenkinsfile
carmen/validate-go-s4.jenkinsfile
carmen/validate-go-s5-archive.jenkinsfile
carmen/validate-go-s5.jenkinsfile
carmen/validate-state-toolchain-archive.jenkinsfile
carmen/validate-state-toolchain-init-archive.jenkinsfile
carmen/validate-state-toolchain-live+archive.jenkinsfile
carmen/validate-state-toolchain-live.jenkinsfile
carmen/validate-witness-proof.jenkinsfile
tosca/validate-evmzero.jenkinsfile
tosca/validate-geth.jenkinsfile
tosca/validate-lfvm-si.jenkinsfile

db-small-ssd -> x86-8-32-m
db-small-nvme -> x86-8-32-m/x86-8-64-l
db-large-nvme -> x86-8-64-xl

Migrate to new agents
