Fantom-foundation/LaScala

- tosca/compliance-tests.jenkinsfile
- tosca/validate-evmzero.jenkinsfile
- tosca/validate-geth.jenkinsfile
- tosca/validate-lfvm-si.jenkinsfile
- tosca/validate-lfvm.jenkinsfile
Limit the memory usage of tosca tests to avoid unreachable agents.
> Add memory limit to tosca tests

- tosca/compliance-tests.jenkinsfile
Before this change, tests run with race detection enables would just log the error and keep running. If a detected race condition is common, this could result in huge logs. With this change, once an issue is detected, the process containing is halted.
> Stop after first detected race condition

- tosca/compliance-tests.jenkinsfile
Execution times are suspiciously long, and these parallel sections cover steps which are parallel themselves. 
Nested parallelism will significantly increase memory usage and force threads to compete for execution.
Please review commit [3efb247381cfa09e13e63c733196e833d147ae23](https://github.com/Fantom-foundation/LaScala/commit/3efb247381cfa09e13e63c733196e833d147ae23) first
Additionally, automatic formatting has been used for the file. This later change can be undone if unwanted.
> Remove parallel sections in Tosca compliance tests pipeline.

- tosca/fuzzing-tests.jenkinsfile
This PR adds a job to execute fuzzing tests as a nightly job.
Fuzzing is a testing mechanism that executes the code with different inputs for the time allowed, it will never end on its own. 
**What does this introduce:**
A jenkins file that builds Tosca, runs unit tests, and starts fuzzing.
The parameter option EntryPoint allows running different tests, as it only makes sense to run one test at the time.
**What does not handle:**
- This does not enable a jenkins job that actually executes the script. An experimental configuration can be found [here](https://scala.fantom.network/job/Tosca/job/Experimental/job/Test-Fuzzer)
**Future work:**
- Go Fuzzing has a mechanism to avoid repeating older runs, to improve domain coverage. To use it, we should cache the folder $home/.cache/go-build …
> Add Tosca fuzzing jenkinsfile

- tosca/fuzzing-tests.jenkinsfile
This PR adds a timeout for the fuzzing tests. After the time duration is expired, the test is considered successful. 
This PR Increases the fuzzing time to 5 hours. To be re-evaluated in the near future. 
Notes: 
- Jenkins will always set the build to red (ABORTED) state when timed-out.
- Fuzzing tests will run forever if no -fuzztime argument is provided.
> Tosca Fuzzing, Allow tests to timeout without failing.

- tosca/compliance-tests.jenkinsfile
Current compliance tests scripts did test CT runs with `go -race` flag enabled. This flag would dramatically increase execution time. 
The test target is to validate thread-safety of the different interpreters implemented using go.
After discussion, the Tosca team came with the trade-off solution of making a partial CT execution with a subset of the rules, to stress the infrastructure in a more manageable execution time.
> Modify compliance tests to avoid overnight timeouts.

- carmen/transient-storage.jenkinsfile
This PR adds `transient-storage.jenkinsfile` which tests `TransientStorage` feature in Carmen.
> Add transient-storage.jenkinsfile

- carmen/fuzzing.jenkinsfile
this PR increases timeout for carmen tests to prevent timeout failures on jenkins
> increases timeout for fuzzing tests

- tosca/validate-evmzero.jenkinsfile
- tosca/validate-geth.jenkinsfile
- tosca/validate-lfvm-si.jenkinsfile
- tosca/validate-lfvm.jenkinsfile
This PR fixes the fetching of the main branch version of Tosca in nightly integration tests.
Before this PR, the scripts did fetch the latest version of Tosca, but override it again with a sub-subsequent submodule update command:
This is part of Tosca's [#692](https://github.com/Fantom-foundation/Tosca/issues/692)
> Fix selection of Tosca main branch for validation tests

- tosca/compliance-tests.jenkinsfile
- tosca/fuzzing-tests.jenkinsfile
- tosca/validate-evmzero.jenkinsfile
- tosca/validate-geth.jenkinsfile
- tosca/validate-lfvm-si.jenkinsfile
- tosca/validate-lfvm.jenkinsfile
For the incoming rust EVM, Tosca make will depend on the rust tool chain.
GCP images include the rust tool chain, but unfortunately it is not in the user PATH. This change adds it manually in each pipeline where Tosca Makefile is invoked (maybe transitively via Aida Makefile) 
blocks https://github.com/Fantom-foundation/Tosca/pull/778
> Tosca pipelines: add rustc to path.

- tosca/fuzzing-lfvm-converter.jenkinsfile
This PR adds a new nightly fuzzing test.
Because of the scope of this test, it is configured to use one hour of time. Last detected failures crashed after few seconds, therefore one hour seems reasonable to start testing. 
Test configuration can be found [here](https://scala.fantom.network/job/Tosca/job/Experimental/job/Test-Fuzzer/31/) (notice that it was manually stopped)
> Add LFVM conversion fuzzer

- tosca/fuzzing-lfvm-converter.jenkinsfile
After the inclusion of rust tool chain in the path for all pipelines using Tosca, this script got merged without the fix. 
This PR adds the required amend to the PATH variable.
> Tosca: Add missing tools to path to fix build

- tosca/fuzzing-tests.jenkinsfile
Several nightly runs of  `Fuzzing Test - FuzzDifferentialLfvmVsGeth` have failed in the last two weeks. 
Every generated regression file has been tested, yielding no logical errors. The issue is attributed to exhausting the system memory. 
This PR reduces the parallel workload of the test, and with it the memory requirements are reduced. 
2/3 of the available cores is an arbitrary number which aims to be conservative in resource usage.
> TOSCA: Reduce fuzzer memory usage by limiting core count.

- tosca/fuzzing-lfvm-converter.jenkinsfile
- GOROOT is no longer needed and may point to the wrong go version
- rust is now in path
> Tosca: Remove unnecessary environment

- tosca/validate-lfvm.jenkinsfile
Parametrize substateDB and chainID in the pipeline in order to use it in release testing in different configurations.
`disableConcurrentBuilds(abortPrevious: false)` was removed to allow multiple parallel executions.
> Parametrize substateDB and chainID in tosca lfvm validation pipeline

- tosca/fuzzing-lfvm-converter.jenkinsfile
- tosca/fuzzing-tests.jenkinsfile
This pr refactors how fuzzing is done in Jenkins: 
- Use new "fuzzing" agent, this limits cores and memory.
- Add persistent cache. To resume fuzzing each time it runs. 
- Add a boolean parameter to clean cache in case it is needed.
Test run here: https://scala.fantom.network/job/Tosca/job/Experimental/job/test-fuzz-new-vm/
- run 9 deletes the cache and start fuzzing
- run 10 catches up fuzzing at number 9232, just where run 9 got interrupted. the counter reaches 9249 when stopped
- run 11 continues from 9249
> Tosca: Refactor fuzzing pipeline

- sonic/geth-state-tests.jenkinsfile
This PR adds jenkinsfile which executes `aida geth-tests` upon all combination of `LFVM/GethVM`, `CarmenDB/GethDB`.
It also creates a directory `sonic` for pipelines regarding the client.
Corresponding [pipeline](https://scala.fantom.network/job/Sonic/job/Aida-Geth-State-Tests/)
> Add geth Sonic tests

- tosca/fuzzing-lfvm-converter.jenkinsfile
This PR fixes the broken syntax inside the lfvm converter fuzzer which lead to failing test runs.
> lfvm converter fuzzer: Fix jenkins file syntax

- sonic/eth-tests.jenkinsfile
This PR fixes path to` ethereum-tests`
It also renames the stage name for better readibility.
> fixes checkout path for ethereum tests

- tosca/race-detection-unit-tests.jenkinsfile
Executing the unit test with race detection was part of the old conformance testing jenkins job. With the refactoring of the jenkins file it has been decided to move this into its own job.
Experimental run: https://scala.fantom.network/job/Tosca/job/Experimental/job/ct-test/11/
> Add jenkinsfile for race detection unit tests

- carmen/fuzzing.jenkinsfile
This PR updates the fuzzing pipeline to store `testdata` after failure so that the tests can be reproduced elsewhere.
> stores testdata on a failing test run

- sonic/eth-tests.jenkinsfile
This PR updates the script that executes ethereum tests agains Sonic. It makes sure that only State Tests are executed as unrelated tests were added to the same directory.
> runs only State Tests

- sonic/race-detection-unit-tests.jenkinsfile
There seem to be some odd interactions between tests when running all the subfolders under the same process space. 
For stability of these checks, unit tests will be run by folders. Go will spawn a process for each and run, all the tests found inside. 
https://scala.fantom.network/job/Sonic/job/Unit-test-race-detection/13
> Prevent race conditions by running tests under the same process

- sonic/eth-tests.jenkinsfile
- sonic/geth-state-tests.jenkinsfile
- tosca/conformance-tests.jenkinsfile
- tosca/fuzzing-lfvm-converter.jenkinsfile
- tosca/fuzzing-tests.jenkinsfile
- tosca/race-detection-unit-tests.jenkinsfile
- tosca/validate-evmzero.jenkinsfile
- tosca/validate-geth.jenkinsfile
- tosca/validate-lfvm-si.jenkinsfile
- tosca/validate-lfvm.jenkinsfile
- utils/template.jenkinsfile
Replace time for the Slack notification with a human-readable format.
> Use currentBuild.durationString for human readable time report

- sonic/race-detection-unit-tests.jenkinsfile
This reverts commit 05e450b88b210c35f48eab5f3d1ab1151eb9c18f.
The assumption was that `go test` was running all tests in a single process. This is not the case. Each package generates a different binary. 
The race condition was identified and fixed :https://github.com/Fantom-foundation/Sonic/pull/283
> Revert #206

- sonic/rpc-tests.jenkinsfile
This PR adds a RPC testing tool for checking, whether client contains needed RPC functions and if they respond with correct result.
This pipeline checkouts and starts fakenet client based on Sonic
Then it runs all the tests and shuts the node down
> Introduce Sonic RPC tests

- utils/rpc-requests.yaml
txpool_content request failed when pool doesn't have any transactions. This PR fixes regex and correctly accept empty pool.
> P04: fix check empty content

- sonic/rpc-tests.jenkinsfile
This PR removes timeout between start of the node and test itself. Test now checks status of the RPC before preforming tests so timeout is not needed anymore.
> Remove timeout from RPC test

- release_testing/operational_tests/P01.jenkinsfile
The following 2 scenarios are added as baseline tests in P01:
- https://github.com/Fantom-foundation/Norma/blob/main/scenarios/test/nodes_net_consistency.yml
- https://github.com/Fantom-foundation/Norma/blob/main/scenarios/test/nodes_start_stop.yml
Tested here: https://scala.fantom.network/job/Norma/job/Experimental/job/P01/job/master/36/
> Add to P01 two more baseline scenarios
